/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe.java;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hp
 */
public class Cafe extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form Cafe
     */
    public Cafe() {
        initComponents();
        
        
        lten.addMouseListener(this);
        lsta.addMouseListener(this);
        lvan.addMouseListener(this);
        lman.addMouseListener(this);
        lfalu.addMouseListener(this);
        lblu.addMouseListener(this);
        lpis.addMouseListener(this);
        lchoco.addMouseListener(this);
        lbis.addMouseListener(this);
        lcoc.addMouseListener(this);
        lwm.addMouseListener(this);
        lpin.addMouseListener(this);
        lcof.addMouseListener(this);
        ltea.addMouseListener(this);
        lsp.addMouseListener(this);
        lorn.addMouseListener(this);
        lpo.addMouseListener(this);
        ldos.addMouseListener(this);
        lsan.addMouseListener(this);
        lnoo.addMouseListener(this);
        lvada.addMouseListener(this);
        lbur.addMouseListener(this);
        ldab.addMouseListener(this);
        lpiz.addMouseListener(this);
    }
    
    DefaultTableModel model = new DefaultTableModel();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lsta = new javax.swing.JLabel();
        lten = new javax.swing.JLabel();
        lvan = new javax.swing.JLabel();
        lman = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lfalu = new javax.swing.JLabel();
        lpis = new javax.swing.JLabel();
        lblu = new javax.swing.JLabel();
        lchoco = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lwm = new javax.swing.JLabel();
        lbis = new javax.swing.JLabel();
        lcoc = new javax.swing.JLabel();
        lpin = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ltea = new javax.swing.JLabel();
        lcof = new javax.swing.JLabel();
        lsp = new javax.swing.JLabel();
        lorn = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lvada = new javax.swing.JLabel();
        lbur = new javax.swing.JLabel();
        ldab = new javax.swing.JLabel();
        lpiz = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ldosa = new javax.swing.JLabel();
        lpo = new javax.swing.JLabel();
        lsan = new javax.swing.JLabel();
        ldos = new javax.swing.JLabel();
        lnoo = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("   THE SIP AND SNACK CAFE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 204));

        lsta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lsta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\strawberry.jpg")); // NOI18N

        lten.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\tender coconut.jpg")); // NOI18N
        lten.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lvan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\vanilla.jpg")); // NOI18N

        lman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lman.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\mango.jpg")); // NOI18N
        lman.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TENDER COCONUT ICE-CREAM");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("STRAWBERRY ICE-CREAM");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("     VANILLA ICE-CREAM");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("         MANGO ICE-CREAM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lten, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lsta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lman, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lten, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("ICE CREAMS", jPanel2);

        lfalu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lfalu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\faluda.jfif")); // NOI18N
        lfalu.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lpis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpis.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\pista.jfif")); // NOI18N

        lblu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\blueberry.jpg")); // NOI18N

        lchoco.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\chocolate.jpg")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("                  FLAUDA");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("  BLUEBERRY ICE-CREAM");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("         PISTA ICE-CREAM");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("CHOCOLATE ICE-CREAM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lfalu, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lchoco, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lchoco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lfalu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpis, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ICE CREAMS", jPanel3);

        lwm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lwm.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\watermelon juice.jfif")); // NOI18N

        lbis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbis.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\water.jfif")); // NOI18N

        lcoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\cococola.jfif")); // NOI18N

        lpin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\pineapple juice.jfif")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("          BISERLI (WATER)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("                  COCO COLA");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("       WATERMELON JUICE");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("        PINEAPPLE JUICE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbis, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lcoc, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lwm, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lpin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lwm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcoc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("DRINKS", jPanel4);

        ltea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltea.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\tea.jfif")); // NOI18N
        ltea.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lcof.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\coffee.jfif")); // NOI18N

        lsp.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\sprite.jfif")); // NOI18N

        lorn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\orange juice.jfif")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("                   COFFEE");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("                     TEA");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("             ORANGE JUICE");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("                     SPRITE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcof, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsp, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lorn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lorn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltea, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcof, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("DRINKS", jPanel5);

        lvada.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\vadapav.jpg")); // NOI18N

        lbur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbur.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\burger.jfif")); // NOI18N

        ldab.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\dabeli.jpg")); // NOI18N

        lpiz.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\pizza.jfif")); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("              VADA PAV");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("                   BURGER");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("                     DABELI");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("                        PIZZA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvada, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbur, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldab, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lpiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvada, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbur, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("SNACKS", jPanel7);

        lpo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\poha.jfif")); // NOI18N

        lsan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\sandwich.jfif")); // NOI18N

        ldos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\dosa.jpg")); // NOI18N

        lnoo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnoo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hp\\Downloads\\noodles.jpg")); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("                  DOSA");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("              SANDWICH");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("                      POHA");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("                 NOODLES");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ldos, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lsan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lpo))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ldosa)
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(342, 342, 342))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ldosa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lpo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lsan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ldos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(1, 1, 1)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lnoo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SNACKS", jPanel6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "PRICE", "QTY", "TOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("TOTAL");

        txtsub.setBackground(new java.awt.Color(255, 204, 204));
        txtsub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsub.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("NAME:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jList1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ICE CREAMS:", "Tender coconut - 60rs", "Strawberry -  30rs", "Vanilla -  25rs", "Mango -  40rs", "Faluda -  35rs", "Blueberry -  60rs ", "Pista -  40rs", "Chocolate -  80rs" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SNACKS:", "Dosa -  60rs", "Poha -  30rs", "Sandwich -  60rs", "Noodles -  100rs", "VadaPav - 30rs", "Burger -  90rs", "Dabeli -  30rs", "Pizza -  120rs" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jList3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "DRINKS:", "Bisleri - 20rs", "CocoCola -  25rs", "Watermelon Juice -  50rs ", "Pineapple Juice - 50rs  ", "Tea -  40rs", "Coffee -  60rs", "Sprite -  20rs", "Orange Juice -  50rs " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("PRICE:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbis;
    private javax.swing.JLabel lblu;
    private javax.swing.JLabel lbur;
    private javax.swing.JLabel lchoco;
    private javax.swing.JLabel lcoc;
    private javax.swing.JLabel lcof;
    private javax.swing.JLabel ldab;
    private javax.swing.JLabel ldos;
    private javax.swing.JLabel ldosa;
    private javax.swing.JLabel lfalu;
    private javax.swing.JLabel lman;
    private javax.swing.JLabel lnoo;
    private javax.swing.JLabel lorn;
    private javax.swing.JLabel lpin;
    private javax.swing.JLabel lpis;
    private javax.swing.JLabel lpiz;
    private javax.swing.JLabel lpo;
    private javax.swing.JLabel lsan;
    private javax.swing.JLabel lsp;
    private javax.swing.JLabel lsta;
    private javax.swing.JLabel ltea;
    private javax.swing.JLabel lten;
    private javax.swing.JLabel lvada;
    private javax.swing.JLabel lvan;
    private javax.swing.JLabel lwm;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
         
        
        if(e.getSource() == lten )
        {
            String name = "Tender Coconut";
            int price = 60;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
        
       else if(e.getSource() == lsta)
        {
            String name = "Strawberry";
            int price = 30;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
        
       else if(e.getSource() == lvan )
        {
            String name = "Vanilla";
            int price = 25;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
        
       else if(e.getSource() == lman )
        {
            String name = "Mango";
            int price = 40;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
        
        else if(e.getSource() == lfalu )
        {
            String name = "Faluda";
            int price = 35;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lblu )
        {
            String name = "Blueberry";
            int price = 60;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lpis )
        {
            String name = "Pista";
            int price = 40;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lchoco )
        {
            String name = "Chocolate";
            int price = 80;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lbis )
        {
            String name = "Bisleri";
            int price = 20;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lcoc )
        {
            String name = "Coco Cola";
            int price = 25;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lwm )
        {
            String name = "Watermelon Juice";
            int price = 50;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        else if(e.getSource() == lpin )
        {
            String name = "Pineapple Juice";
            int price = 50;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3));
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
else if(e.getSource() == lcof )
        {
            String name = "Coffee";
            int price = 60;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty").toString());
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == ltea )
        {
            String name = "Tea";
            int price = 40;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lsp )
        {
            String name = "Sprite";
            int price = 20;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lorn )
        {
            String name = "Orange Juice";
            int price = 50;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        

        else if(e.getSource() == ldos )
        {
            String name = "Dosa";
            int price = 60;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lpo )
        {
            String name = "Poha";
            int price = 30;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }
        
        
        
        
        
        else if(e.getSource() == lsan )
        {
            String name = "Sandwich";
            int price = 60;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lnoo )
        {
            String name = "Noodles";
            int price = 100;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lvada )
        {
            String name = "VadaPav";
            int price = 30;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lbur )
        {
            String name = "Burger";
            int price = 90;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == ldab )
        {
            String name = "Dabeli";
            int price = 30;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        else if(e.getSource() == lpiz )
        {
            String name = "Pizza";
            int price = 120;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter the qty"));
            int tot = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]
            {
            
                name,
                price,
                qty,
                tot,
            });
            
            
            int sum = 0;
            for(int i = 0; i <jTable1.getRowCount(); i++)
            {
                
                sum = sum + Integer.parseInt((String) jTable1.getValueAt(i, 3).toString());
                
            }
            
            txtsub.setText(Integer.toString(sum));
            }

        
        
        
        
        
            }

    @Override
    public void mousePressed(MouseEvent e) {
        
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }
}
